# image will be published to ghcr.io/<user>/<name>
name: os-470xx
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 38-470 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README
      - etc: /etc

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - bash-color-prompt
      - code
      - ddccontrol
      - ddccontrol-db
      - ddccontrol-gtk
      - input-remapper
      - libvirt
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - steam-devices
      - tmux
      - tailscale
      - virt-manager
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - gnome-software-rpm-ostree
      - gnome-tour

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      # - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, yafti and it's dependencies (pip & libadwaita)
                #  will be installed and set up
    custom-flatpaks: # this section is optional
      - Boxes: org.gnome.Boxes
      - Brave: com.brave.Browser
      - Clapper: com.github.rafostar.Clapper
      - Discord: com.discordapp.Discord
      - Firefox: org.mozilla.firefox
      - LibreOffice: org.libreoffice.LibreOffice
      - MKVToolnix: org.bunkus.mkvtoolnix-gui
      - Spotify: com.spotify.Client
      - Steam: com.valvesoftware.Steam

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
